# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mosgotours
email: info@mosgotours.com
description: > # this means to ignore newlines until "baseurl:"
  Lomonosov MSU Free Walking Tour
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mosgotours.tk" # the base hostname & protocol for your site, e.g. http://example.com
address: 
phone: +7 (987) 654-32-10
twitter_username: mosgotours
github_username:  mosgotours

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

navigation:
  - text:       Guides
    url:        /guides/ 
  - text:       Tours 
    url:        /tours/
  - text:       Home 
    url:        /

guides:
  - name: Anna
    avatar: /images/avatar_anna.jpg
    description: > 
      Anna has herself experienced MSU from different points of view as a young child taken for a walk around the campus 
      by her father, himself an MSU graduate, as a schoolgirl coming for math classes and getting lost in the Main Building 
      (wanna hear some spooky stories about the university? She's the one to ask), as a Young Philologist School pupil and 
      now as a third year student of linguistics and literature. She's an easy-going scientist ready to help you fall in love 
      with MSU, and she sure has done her research! Do you want to know what an 18-century professor would look like? Which 
      student tradition involves a huge annual snowball battle? What the MSU Main Building has in common with the National 
      Theatre in London? Interested in history? Biotechnology? Poetry? Paragliding? Come and ask Anna! She's the perfect 
      person to help you explore both the historic and the modern bits of university life.
    languages: English, Russian
    tour: Lomonosov MSU
